apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 504807027420.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 504807027420.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 8b275e5b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
